CRUDCORE/Models/ContactoModel.cs
using System.ComponentModel.DataAnnotations;

namespace CRUDCORE.Models
{
    public class ContactoModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage ="El campo Nombre es obligatorio")]
        public string? Nombre { get; set; }

        [Required(ErrorMessage = "El campo Concentracion es obligatorio")]
        public string? Concentracion { get; set; }

        public int IdFormaFarmaceutica { get; set; }

        public string? FormasFarmaceuticas { get; set; }

        [Required(ErrorMessage = "El campo Precio es obligatorio")]
        public string? Precio { get; set; }

        [Required(ErrorMessage = "El campo Stock es obligatorio")]
        public string? Stock { get; set; }

        [Required(ErrorMessage = "El campo Presentacion es obligatorio")]
        public string? Presentacion { get; set; }

        public string? Estatus { get; set; }

        public int IdEstatus { get; set; }

    }
}

CRUDCORE/Models/ErrorViewModel.cs
namespace CRUDCORE.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CRUDCORE/Models/UsuarioModel.cs
using System.ComponentModel.DataAnnotations;

namespace CRUDCORE.Models
{
    public class UsuarioModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage ="El campo Nombre es obligatorio")]
        public string? Nombre { get; set; }

        public string? FechaCreacion { get; set; }

        public int IdPerfil { get; set; }

        public string? Usuario { get; set; }

        public string? Password { get; set; }

        public string? Estatus { get; set; }

        public int IdEstatus { get; set; }

    }
}

CRUDCORE/Controllers/HomeController.cs
using CRUDCORE.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CRUDCORE.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CRUDCORE/Controllers/MantenedorController.cs
using Microsoft.AspNetCore.Mvc;

using CRUDCORE.Datos;
using CRUDCORE.Models;

namespace CRUDCORE.Controllers
{
    public class MantenedorController : Controller
    {

        ContactoDatos _ContactoDatos = new ContactoDatos();

        public IActionResult Listar()
        {
            //LA VISTA MOSTRARÁ UNA LISTA DE CONTACTOS
            var oLista = _ContactoDatos.Listar();

            return View(oLista);
        }

        public IActionResult Guardar()
        {
            //METODO SOLO DEVUELVE LA VISTA
            return View();
        }

        [HttpPost]
        public IActionResult Guardar(ContactoModel oContacto)
        {
            //METODO RECIBE EL OBJETO PARA GUARDARLO EN BD
            if (!ModelState.IsValid)
                return View();


            var respuesta = _ContactoDatos.Guardar(oContacto);

            if (respuesta)
                return RedirectToAction("Listar");
            else 
                return View();
        }

        public IActionResult Editar(int Id)
        {
            //METODO SOLO DEVUELVE LA VISTA
            var ocontacto = _ContactoDatos.Obtener(Id);
            return View(ocontacto);
        }

        [HttpPost]
        public IActionResult Editar(ContactoModel oContacto)
        {
            if (!ModelState.IsValid)
                return View();


            var respuesta = _ContactoDatos.Editar(oContacto);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }


        public IActionResult Eliminar(int Id)
        {
            //METODO SOLO DEVUELVE LA VISTA
            var ocontacto = _ContactoDatos.Obtener(Id);
            return View(ocontacto);
        }

        [HttpPost]
        public IActionResult Eliminar(ContactoModel oContacto)
        {
  
            var respuesta = _ContactoDatos.Eliminar(oContacto.Id);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

    }
}

CRUDCORE/Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Mvc;

using CRUDCORE.Datos;
using CRUDCORE.Models;

namespace CRUDCORE.Controllers
{
    public class UsuariosController : Controller
    {

        UsuarioDatos _UsuarioDatos = new UsuarioDatos();

        public IActionResult Listar()
        {
            //LA VISTA MOSTRARÁ UNA LISTA DE CONTACTOS
            var oLista = _UsuarioDatos.Listar();

            return View(oLista);
        }

        public IActionResult Guardar()
        {
            //METODO SOLO DEVUELVE LA VISTA
            return View();
        }

        [HttpPost]
        public IActionResult Guardar(UsuarioModel oUsuario)
        {
            //METODO RECIBE EL OBJETO PARA GUARDARLO EN BD
            if (!ModelState.IsValid)
                return View();


            var respuesta = _UsuarioDatos.Guardar(oUsuario);

            if (respuesta)
                return RedirectToAction("Listar");
            else 
                return View();
        }

        public IActionResult Editar(int Id)
        {
            //METODO SOLO DEVUELVE LA VISTA
            var oUsuario = _UsuarioDatos.Obtener(Id);
            return View(oUsuario);
        }

        [HttpPost]
        public IActionResult Editar(UsuarioModel oUsuario)
        {
            if (!ModelState.IsValid)
                return View();


            var respuesta = _UsuarioDatos.Editar(oUsuario);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }


        public IActionResult Eliminar(int Id)
        {
            //METODO SOLO DEVUELVE LA VISTA
            var oUsuario = _UsuarioDatos.Obtener(Id);
            return View(oUsuario);
        }

        [HttpPost]
        public IActionResult Eliminar(UsuarioModel oUsuario)
        {
  
            var respuesta = _UsuarioDatos.Eliminar(oUsuario.Id);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

    }
}

CRUDCORE/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CRUDCORE/Views/Mantenedor/Editar.cshtml
@model ContactoModel
@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card">
  <div class="card-header">
    Editar Medicamento
  </div>
  <div class="card-body">
    

      <form asp-action="Editar" asp-controller="Mantenedor" method="post">

          <input asp-for="Id" type="hidden" class="form-control">
          <div class="mb-3">
              <label class="form-label">Nombre</label>
              <input asp-for="Nombre" type="text" class="form-control">
              <span asp-validation-for="Nombre" class="text-danger"></span>
          </div>
          <div class="mb-3">
              <label class="form-label">Concentracion</label>
              <input asp-for="Concentracion" type="text" class="form-control">
              <span asp-validation-for="Concentracion" class="text-danger"></span>
          </div>
          <div class="mb-3">
              <label class="form-label">FormaFarmaceutica</label>
              <select class="form-control" name="IdFormaFarmaceutica" runat="server" id="IdFormaFarmaceutica" asp-for="IdFormaFarmaceutica">
                  <option value="1">TABLETA</option>
                  <option value="2">PASTILLA</option>
                  <option value="3">JARABE</option>
              </select>
          </div>

          <div class="mb-3">
              <label class="form-label">Precio</label>
              <input asp-for="Precio" type="text" class="form-control">
              <span asp-validation-for="Precio" class="text-danger"></span>
          </div>
          <div class="mb-3">
              <label class="form-label">Stock</label>
              <input asp-for="Stock" type="text" class="form-control">
              <span asp-validation-for="Stock" class="text-danger"></span>
          </div>
          <div class="mb-3">
              <label class="form-label">FormaFarmaceutica</label>
              <select class="form-control" name="IdEstatus" runat="server" id="IdEstatus" asp-for="IdEstatus">
                  <option value="1">Activo</option>
                  <option value="0">InActivo</option>
              </select>
          </div>
          <button type="submit" class="btn btn-primary">Guardar</button>
          <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-warning">Volver a la lista</a>
      </form>


  </div>
</div>

CRUDCORE/Views/Mantenedor/Eliminar.cshtml
@model UsuarioModel
@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card">
  <div class="card-header">
    Eliminar Usuario
  </div>
  <div class="card-body">
    

      <form asp-action="Eliminar" asp-controller="Usuarios" method="post">

       <input asp-for="Id" type="hidden" class="form-control">

       <div class="alert alert-danger" role="alert">
          ¿Desea eliminar el contacto : @Html.DisplayTextFor(m => m.Nombre) ?
        </div>
   
      <button type="submit" class="btn btn-danger">Elimnar</button>
      <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-warning">Volver a la lista</a>
    </form>


  </div>
</div>

CRUDCORE/Views/Mantenedor/Guardar.cshtml
@model ContactoModel
@{
    ViewData["Title"] = "Guardar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
  <div class="card-header">
    Crear Medicamento
  </div>
  <div class="card-body">
    

      <form asp-action="Guardar" asp-controller="Mantenedor" method="post">
      <div class="mb-3">
        <label class="form-label">Nombre</label>
        <input asp-for="Nombre" type="text" class="form-control">
        <span asp-validation-for="Nombre" class="text-danger"></span>
      </div>
      <button type="submit" class="btn btn-primary">Guardar</button>
      <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-warning">Volver a la lista</a>
    </form>


  </div>
</div>

CRUDCORE/Views/Mantenedor/Listar.cshtml
@model List<ContactoModel>
@{
    ViewData["Title"] = "Listar Medicamentos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="card">
  <div class="card-header">
    Lista Medicamentos
  </div>
  <div class="card-body">
    
    <div class="table-responsive">
        <table id="myTable" class="table table-bordered">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Concentracion</th>
                    <th>FormasFarmaceuticas</th>
                    <th>Precio</th>
                    <th>Stock</th>
                    <th>Presentacion</th>
                    <th>Estatus</th>
                    <th>Acciones</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.Nombre</td>
                        <td>@item.Concentracion</td>
                        <td>@item.FormasFarmaceuticas</td>
                        <td>@item.Precio</td>
                        <td>@item.Stock</td>
                        <td>@item.Presentacion</td>
                        <td>@item.Estatus</td>

                        <td>
                            <a asp-action="Editar" asp-controller="Mantenedor" class="btn btn-primary btn-sm" asp-route-Id="@item.Id">Editar</a>
                            <a asp-action="Eliminar" asp-controller="Mantenedor" class="btn btn-danger btn-sm" asp-route-Id="@item.Id">Eliminar</a>
                        </td>
                    </tr>

                }
            </tbody>
        </table>
    </div>

  </div>
</div>

CRUDCORE/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Prueba</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CRUDCORE.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdn.datatables.net/2.0.3/css/dataTables.dataTables.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Mantenedor" asp-action="/">Medicamentos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mantenedor" asp-action="">Medicamentos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="">Usuarios</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/2.0.3/js/dataTables.min.js"></script>
    <script>
        let table = new DataTable('#myTable');
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CRUDCORE/Views/Usuarios/Editar.cshtml
@model UsuarioModel
@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card">
  <div class="card-header">
    Editar Usuario
  </div>
  <div class="card-body">
    

      <form asp-action="Editar" asp-controller="Usuarios" method="post">

          <input asp-for="Id" type="hidden" class="form-control">
          <div class="mb-3">
              <label class="form-label">Nombre</label>
              <input asp-for="Nombre" type="text" class="form-control">
              <span asp-validation-for="Nombre" class="text-danger"></span>
          </div>
          <div class="mb-3">
              <label class="form-label">Fecha de Creacion</label>
              <input asp-for="FechaCreacion" type="datetime" class="form-control">
              <span asp-validation-for="FechaCreacion" class="text-danger"></span>
          </div>

          <div class="mb-3">
              <label class="form-label">Usuario</label>
              <input asp-for="Usuario" type="text" class="form-control">
              <span asp-validation-for="Usuario" class="text-danger"></span>
          </div>
          <div class="mb-3">
              <label class="form-label">Password</label>
              <input asp-for="Password" type="text" class="form-control">
              <span asp-validation-for="Password" class="text-danger"></span>
          </div>
          <div class="mb-3">
              <label class="form-label">Estatus</label>
              <select class="form-control" name="IdEstatus" runat="server" id="IdEstatus" asp-for="IdEstatus">
                  <option value="1">Activo</option>
                  <option value="0">InActivo</option>
              </select>
          </div>
          <button type="submit" class="btn btn-primary">Guardar</button>
          <a asp-action="Listar" asp-controller="Usuarios" class="btn btn-warning">Volver a la lista</a>
      </form>


  </div>
</div>

CRUDCORE/Views/Usuarios/Eliminar.cshtml
@model ContactoModel
@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card">
  <div class="card-header">
    Eliminar Medicamento
  </div>
  <div class="card-body">
    

      <form asp-action="Eliminar" asp-controller="Usuarios" method="post">

       <input asp-for="Id" type="hidden" class="form-control">

       <div class="alert alert-danger" role="alert">
          ¿Desea eliminar el contacto : @Html.DisplayTextFor(m => m.Nombre) ?
        </div>
   
      <button type="submit" class="btn btn-danger">Elimnar</button>
      <a asp-action="Listar" asp-controller="Usuarios" class="btn btn-warning">Volver a la lista</a>
    </form>


  </div>
</div>

CRUDCORE/Views/Usuarios/Guardar.cshtml
@model ContactoModel
@{
    ViewData["Title"] = "Guardar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
  <div class="card-header">
    Crear Medicamento
  </div>
  <div class="card-body">
    

      <form asp-action="Guardar" asp-controller="Usuarios" method="post">
      <div class="mb-3">
        <label class="form-label">Nombre</label>
        <input asp-for="Nombre" type="text" class="form-control">
        <span asp-validation-for="Nombre" class="text-danger"></span>
      </div>
      <button type="submit" class="btn btn-primary">Guardar</button>
      <a asp-action="Listar" asp-controller="Usuarios" class="btn btn-warning">Volver a la lista</a>
    </form>


  </div>
</div>

CRUDCORE/Views/Usuarios/Listar.cshtml
@model List<UsuarioModel>
@{
    ViewData["Title"] = "Listar Usuarios";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="card">
  <div class="card-header">
    Lista Usuarios
  </div>
  <div class="card-body">
    
    <div class="table-responsive">
        <table id="myTable" class="table table-bordered">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>FechaCreacion</th>
                    <th>Usuario</th>
                    <th>Estatus</th>
                    <th>Acciones</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.Nombre</td>
                        <td>@item.FechaCreacion</td>
                        <td>@item.Usuario</td>
                        <td>@item.Estatus</td>

                        <td>
                            <a asp-action="Editar" asp-controller="Usuarios" class="btn btn-primary btn-sm" asp-route-Id="@item.Id">Editar</a>
                            <a asp-action="Eliminar" asp-controller="Usuarios" class="btn btn-danger btn-sm" asp-route-Id="@item.Id">Eliminar</a>
                        </td>
                    </tr>

                }
            </tbody>
        </table>
    </div>

  </div>
</div>